### ISSUE TITLE
the .out file is empty

### ISSUE THREAD

**Issue by xiaozhhenu** [APSIMInitiative/APSIMClassic#1852] opened 2020-05-05 08:28 UTC
I had made a simulation in the apsim, when the simulation is finish, the .out file is empty, and in the summaryfile section, no error was find. What is the reason for this situation.

**Comment by BenAbabaei** [comment] 2020-05-05 12:13
How many years were simulated? If one, did you have long enough weather data?

**Comment by xiaozhhenu** [comment] 2020-05-05 13:15
> How many years were simulated? If one, did you have long enough weather data?

Thanks for your reply. The simulation was start from 2004 to 2010, and I had all the weather data in the simulation. Is this situation caused by weather data?

**Comment by BenAbabaei** [comment] 2020-05-05 13:54
Hard to say without having the Apsim file, met file and summary file. Could you please put them all in a zip file and upload here?

**Comment by xiaozhhenu** [comment] 2020-05-06 10:46
> Hard to say without having the Apsim file, met file and summary file. Could you please put them all in a zip file and upload here?

Thanks for your help, I had upload all the files you need, If i got something wrong, please let me know.
[fq.zip](https://github.com/APSIMInitiative/APSIMClassic/files/4586202/fq.zip)

**Comment by BenAbabaei** [comment] 2020-05-06 11:31
[fq.zip](https://github.com/APSIMInitiative/APSIMClassic/files/4586410/fq.zip)

I am not quite sure why the .NET manager does not work. I have never used that kind of managers before. If you go to Example folder in APSIM directory and open Maize with SWMM, you can copy and use the manager folder. It uses classic manager scripts instead of .NET manager. 
You also need to fix the XF values in soil Water, as they are all zero. Zero means no penetration of roots in the soil layer.
You may also need some irrigation. I tested your file with Auto Irrigation On. 

Please remember that I have changed some parameters. You may need to double check the values.

**Comment by peter-devoil** [comment] 2020-05-06 22:37
This run is silently crashing - there's no "end of simulation ..." message - just the maize crop starting, then ... nothing. 

There's a [fix](https://github.com/APSIMInitiative/APSIMClassic/issues/1812) for this - you can get it from the [upgrades page](https://apsimdev.apsim.info/APSIM.Registration.Portal/Main.aspx).

**Comment by xiaozhhenu** [comment] 2020-05-11 10:29
> 
> 
> [fq.zip](https://github.com/APSIMInitiative/APSIMClassic/files/4586410/fq.zip)
> 
> I am not quite sure why the .NET manager does not work. I have never used that kind of managers before.
> If you go to Example folder in APSIM directory and open Maize with SWMM, you can copy and use the manager folder (I did in the attached file). It uses classic manager scripts instead of .NET manager.
> You also need to fix the XF values in soil Water, as they are all zero. Zero means no penetration of roots in the soil layer.
> You may also need some irrigation. I tested your file with Auto Irrigation On. Further, you need to have a Reporting Frequency under output file.
> 
> Please remember that I have changed some parameters. You may need to double check the values.

Thanks, I'm very  appreciate for your help

**Comment by xiaozhhenu** [comment] 2020-05-11 10:30
> 
> 
> This run is silently crashing - there's no "end of simulation ..." message - just the maize crop starting, then ... nothing.
> 
> There's a [fix](https://github.com/APSIMInitiative/APSIMClassic/issues/1812) for this - you can get it from the [upgrades page](https://apsimdev.apsim.info/APSIM.Registration.Portal/Main.aspx).

Thanks for your valuable suggestions

**Comment by peter-devoil** [comment] 2020-05-11 23:10
Not a problem. If the issue is resolved, you can close it.. P

**Closed** 2020-05-12 01:14 UTC
Labels: question
